- name: Pull and Run docker image
  hosts: ubuntu18
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull mudit219/spe-calculator
      docker_image:
        name: mudit219/spe-calculator
        source: pull


